// <auto-generated />
using System;
using HR_Platform.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HR_Platform.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250706013408_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HR_Platform.Data.Entities.JobCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobCandidates");
                });

            modelBuilder.Entity("HR_Platform.Data.Entities.JobCandidateSkill", b =>
                {
                    b.Property<Guid>("JobCandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JobCandidateId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("JobCandidateSkills");
                });

            modelBuilder.Entity("HR_Platform.Data.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("HR_Platform.Data.Entities.JobCandidateSkill", b =>
                {
                    b.HasOne("HR_Platform.Data.Entities.JobCandidate", "JobCandidate")
                        .WithMany("Skills")
                        .HasForeignKey("JobCandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR_Platform.Data.Entities.Skill", "Skill")
                        .WithMany("JobCandidates")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobCandidate");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("HR_Platform.Data.Entities.JobCandidate", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("HR_Platform.Data.Entities.Skill", b =>
                {
                    b.Navigation("JobCandidates");
                });
#pragma warning restore 612, 618
        }
    }
}
